url_room = 'https://api-edu.skysmart.ru/api/v1/task/preview'
url_auth = 'https://api-edu.skysmart.ru/api/v2/auth/auth/student'
url_steps = 'https://api-edu.skysmart.ru/api/v1/content/step/load?stepUuid='
url_register = 'https://api-edu.skysmart.ru/api/v3/user/registration/teacher'
url_room_preview = 'https://api-edu.skysmart.ru/api/v1/task/preview'